In [164]:
import pandas as pd
import numpy as np
import math

In [165]:
train=pd.read_csv('cipla\\dataset\\train.csv')

In [166]:
print(train.isna().sum())

Customer ID                       0
Name                              0
Gender                           53
Age                               0
Income (USD)                   4576
Income Stability               1683
Profession                        0
Type of Employment             7270
Location                          0
Loan Amount Request (USD)         0
Current Loan Expenses (USD)     172
Expense Type 1                    0
Expense Type 2                    0
Dependents                     2493
Credit Score                   1703
No. of Defaults                   0
Has Active Credit Card         1566
Property ID                       0
Property Age                   4850
Property Type                     0
Property Location               356
Co-Applicant                      0
Property Price                    0
Loan Sanction Amount (USD)      340
dtype: int64


In [167]:
train=train[train['Loan Sanction Amount (USD)'].notna()]

In [168]:
col=train.columns

In [169]:
for c in col:
    if train[c].isna().sum()>0:
        if train[c].dtype=='float64':
            train[c]=train[c].fillna(train[c].mean())
        elif train[c].dtype=='int64':
            train[c]=train[c].fillna(train[c].mean())

In [170]:
train['Gender'] = train['Gender'].replace(np.nan, 'Unspecified')
train['Income Stability'] = train['Income Stability'].fillna(train['Income Stability'].mode().iloc[0])
train['Type of Employment'] = train['Type of Employment'].fillna(train['Type of Employment'].mode().iloc[0])
train['Has Active Credit Card'] = train['Has Active Credit Card'].fillna(train['Has Active Credit Card'].mode().iloc[0])
train['Property Location'] = train['Property Location'].fillna(train['Property Location'].mode().iloc[0])


In [171]:
print(train.isna().sum())

Customer ID                    0
Name                           0
Gender                         0
Age                            0
Income (USD)                   0
Income Stability               0
Profession                     0
Type of Employment             0
Location                       0
Loan Amount Request (USD)      0
Current Loan Expenses (USD)    0
Expense Type 1                 0
Expense Type 2                 0
Dependents                     0
Credit Score                   0
No. of Defaults                0
Has Active Credit Card         0
Property ID                    0
Property Age                   0
Property Type                  0
Property Location              0
Co-Applicant                   0
Property Price                 0
Loan Sanction Amount (USD)     0
dtype: int64


In [172]:
# for col in ['Customer ID', 'Name', 'Gender', 'Income Stability','Profession','Type of Employment','Location','Expense Type 1','Expense Type 2','Has Active Credit Card','Property Location']:
#     train[col] = train[col].astype('category').cat.codes

In [173]:
X = train[['Current Loan Expenses (USD)', 'Customer ID', 'Property Price', 'Loan Amount Request (USD)', 'Credit Score', 'Income Stability', 'Dependents', 'Expense Type 2', 'Location', 'Profession', 'Age']]
y = train.iloc[:, -1].values

In [174]:
print(X.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29660 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Current Loan Expenses (USD)  29660 non-null  float64
 1   Customer ID                  29660 non-null  object 
 2   Property Price               29660 non-null  float64
 3   Loan Amount Request (USD)    29660 non-null  float64
 4   Credit Score                 29660 non-null  float64
 5   Income Stability             29660 non-null  object 
 6   Dependents                   29660 non-null  float64
 7   Expense Type 2               29660 non-null  object 
 8   Location                     29660 non-null  object 
 9   Profession                   29660 non-null  object 
 10  Age                          29660 non-null  int64  
dtypes: float64(5), int64(1), object(5)
memory usage: 2.7+ MB
None


In [175]:
print(X['Income Stability'].value_counts())

Low     27116
High     2544
Name: Income Stability, dtype: int64


In [176]:
X=X.values

In [177]:
'''from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
# ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
# ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
# ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')

# X=X.reshape(-1,1)
# X.iloc[:,1] = ct1.fit_transform(X.iloc[:,1])
# X.iloc[:,5] = ct1.fit_transform(X.iloc[:,5])
# X.iloc[:,7] = ct1.fit_transform(X.iloc[:,7])
# X.iloc[:,8] = ct1.fit_transform(X.iloc[:,8])
# X.iloc[:,9] = ct1.fit_transform(X.iloc[:,9])
ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,5,7,8,9])], remainder='passthrough')
X=np.array(X)
X = ct1.fit_transform(X)
print(X)
'''


"from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\n# ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')\n# ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')\n# ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')\n# ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')\n# ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')\n\n# X=X.reshape(-1,1)\n# X.iloc[:,1] = ct1.fit_transform(X.iloc[:,1])\n# X.iloc[:,5] = ct1.fit_transform(X.iloc[:,5])\n# X.iloc[:,7] = ct1.fit_transform(X.iloc[:,7])\n# X.iloc[:,8] = ct1.fit_transform(X.iloc[:,8])\n# X.iloc[:,9] = ct1.fit_transform(X.iloc[:,9])\nct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,5,7,8,9])], remainder='passthrough')\nX=np.array(X)\nX = ct1

In [178]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
X[:,5] = le.fit_transform(X[:,5])
X[:,7] = le.fit_transform(X[:,7])
X[:,8] = le.fit_transform(X[:,8])
X[:,9] = le.fit_transform(X[:,9])
print(X)

[[241.08 17817 119933.46 ... 1 7 56]
 [495.81 15819 54791.0 ... 1 7 32]
 [171.95 18289 72440.58 ... 1 3 65]
 ...
 [583.11 26625 102108.02 ... 2 7 49]
 [378.29 1399 168194.47 ... 1 7 38]
 [693.94 15148 194512.6 ... 0 3 63]]


In [179]:
#print(X.shape)

In [180]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [181]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [182]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [183]:
y_pred=regressor.predict(X_test)


In [184]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 39372.669  38121.4  ]
 [ 69764.736  77125.86 ]
 [285612.711 313502.39 ]
 ...
 [ 21859.396  25674.22 ]
 [ 17517.661   -999.   ]
 [     0.         0.   ]]


In [185]:
from sklearn.metrics import r2_score,mean_squared_error,explained_variance_score

In [186]:
print(r2_score(y_test,y_pred))


0.9131745826939108


In [187]:
print(math.sqrt(mean_squared_error(y_test,y_pred)))
print(explained_variance_score(y_test,y_pred))

14047.644153837246
0.9132354447522197


In [188]:
test=pd.read_csv('cipla\\dataset\\test.csv')

In [189]:
test1=test.copy()

In [190]:
print(test.isna().sum())

Customer ID                       0
Name                              0
Gender                           31
Age                               0
Income (USD)                    750
Income Stability                813
Profession                        0
Type of Employment             4689
Location                          0
Loan Amount Request (USD)         0
Current Loan Expenses (USD)      83
Expense Type 1                    0
Expense Type 2                    0
Dependents                     1142
Credit Score                    743
No. of Defaults                   0
Has Active Credit Card         1076
Property ID                       0
Property Age                    892
Property Type                     0
Property Location               160
Co-Applicant                      0
Property Price                    0
dtype: int64


In [191]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Customer ID                  20000 non-null  object 
 1   Name                         20000 non-null  object 
 2   Gender                       19969 non-null  object 
 3   Age                          20000 non-null  int64  
 4   Income (USD)                 19250 non-null  float64
 5   Income Stability             19187 non-null  object 
 6   Profession                   20000 non-null  object 
 7   Type of Employment           15311 non-null  object 
 8   Location                     20000 non-null  object 
 9   Loan Amount Request (USD)    20000 non-null  float64
 10  Current Loan Expenses (USD)  19917 non-null  float64
 11  Expense Type 1               20000 non-null  object 
 12  Expense Type 2               20000 non-null  object 
 13  Dependents      

In [192]:
test['Property Price'] = test['Property Price'].str.replace('?', '-1')
test['Co-Applicant'] = test['Co-Applicant'].str.replace('?', '-1')


<ipython-input-192-1948a2c015a0>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  test['Property Price'] = test['Property Price'].str.replace('?', '-1')
<ipython-input-192-1948a2c015a0>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  test['Co-Applicant'] = test['Co-Applicant'].str.replace('?', '-1')


In [193]:
test['Property Price']=test['Property Price'].astype(np.float64)
test['Co-Applicant']=test['Co-Applicant'].astype(np.int64)


In [194]:
col1=test.columns

for c in col1:
    if test[c].isna().sum()>1:
        if test[c].dtype=='float64':
            test[c]=test[c].fillna(test[c].mean())
        elif test[c].dtype=='int64':
            test[c]=test[c].fillna(test[c].mean)

In [195]:
test['Gender'] = test['Gender'].replace(np.nan, 'Unspecified')
test['Income Stability'] = test['Income Stability'].fillna(test['Income Stability'].mode().iloc[0])
test['Type of Employment'] = test['Type of Employment'].fillna(test['Type of Employment'].mode().iloc[0])
test['Has Active Credit Card'] = test['Has Active Credit Card'].fillna(test['Has Active Credit Card'].mode().iloc[0])
test['Property Location'] = test['Property Location'].fillna(test['Property Location'].mode().iloc[0])

In [196]:
test = test[['Current Loan Expenses (USD)', 'Customer ID', 'Property Price', 'Loan Amount Request (USD)', 'Credit Score', 'Income Stability', 'Dependents', 'Expense Type 2', 'Location', 'Profession', 'Age']]


In [197]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Current Loan Expenses (USD)  20000 non-null  float64
 1   Customer ID                  20000 non-null  object 
 2   Property Price               20000 non-null  float64
 3   Loan Amount Request (USD)    20000 non-null  float64
 4   Credit Score                 20000 non-null  float64
 5   Income Stability             20000 non-null  object 
 6   Dependents                   20000 non-null  float64
 7   Expense Type 2               20000 non-null  object 
 8   Location                     20000 non-null  object 
 9   Profession                   20000 non-null  object 
 10  Age                          20000 non-null  int64  
dtypes: float64(5), int64(1), object(5)
memory usage: 1.7+ MB
None


In [198]:
test=test.values
test[:,1] = le.fit_transform(test[:,1])
test[:,5] = le.fit_transform(test[:,5])
test[:,7] = le.fit_transform(test[:,7])
test[:,8] = le.fit_transform(test[:,8])
test[:,9] = le.fit_transform(test[:,9])

In [199]:
test=sc.transform(test)

In [200]:
final=regressor.predict(test)

In [201]:
print(final)

[103345.256  78614.327      0.    ...  11522.573  64528.211  77849.074]


In [202]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(regressor, X_test, y_test, scoring='r2', cv=cv, n_jobs=-1, error_score='raise')

In [203]:
print('r2: %.3f (%.3f)' % (np.mean(n_scores), np.std(n_scores)))

r2: 0.893 (0.026)


In [204]:
final=pd.Series(final,name='Loan Sanction Amount (USD)')

In [205]:
output=pd.concat([test1['Customer ID'],final],axis=1)

In [206]:
print(output.head())

  Customer ID  Loan Sanction Amount (USD)
0     C-26247                  103345.256
1     C-35067                   78614.327
2     C-34590                       0.000
3     C-16668                   71608.961
4     C-12196                   71065.366


In [207]:
print(min(output['Loan Sanction Amount (USD)']))

-599.4


In [208]:
output.to_csv('submission.csv',index=False)

In [209]:
print(output.groupby('Loan Sanction Amount (USD)').count())

                            Customer ID
Loan Sanction Amount (USD)             
-599.400                              1
-499.500                              7
-399.600                              7
-299.700                             15
-199.800                             48
...                                 ...
 275798.464                           1
 286475.291                           1
 289116.529                           1
 310611.187                           1
 351749.856                           1

[17479 rows x 1 columns]


In [259]:
new_df = train.groupby('Income Stability').apply(lambda x: x.sample(n=2544)).reset_index(drop = True)

new_df['Income Stability'].value_counts()



High    2544
Low     2544
Name: Income Stability, dtype: int64

In [260]:
new_df = new_df[['Current Loan Expenses (USD)', 'Customer ID', 'Property Price', 'Loan Amount Request (USD)', 'Credit Score', 'Income Stability', 'Dependents', 'Expense Type 2', 'Location', 'Profession', 'Age','Loan Sanction Amount (USD)']]


In [261]:
print(new_df.head())

   Current Loan Expenses (USD) Customer ID  Property Price  \
0                       925.50     C-39901       256066.32   
1                       134.33      C-7265        43879.02   
2                       147.29     C-17828        36881.86   
3                       207.52     C-28295        45484.33   
4                       381.53     C-42465       194894.61   

   Loan Amount Request (USD)  Credit Score Income Stability  Dependents  \
0                  206762.45        738.56             High         2.0   
1                   26429.23        868.89             High         1.0   
2                   31521.70        645.09             High         4.0   
3                   36058.71        833.06             High         2.0   
4                  128115.45        802.22             High         1.0   

  Expense Type 2    Location Profession  Age  Loan Sanction Amount (USD)  
0              Y  Semi-Urban  Pensioner   63                   144733.72  
1              Y       Urb

In [262]:
print(new_df.isna().sum())

Current Loan Expenses (USD)    0
Customer ID                    0
Property Price                 0
Loan Amount Request (USD)      0
Credit Score                   0
Income Stability               0
Dependents                     0
Expense Type 2                 0
Location                       0
Profession                     0
Age                            0
Loan Sanction Amount (USD)     0
dtype: int64


In [263]:
X_new=new_df.iloc[:,:-1].values
y_new=new_df.iloc[:,-1].values

In [264]:

X_new[:,1] = le.fit_transform(X_new[:,1])
X_new[:,5] = le.fit_transform(X_new[:,5])
X_new[:,7] = le.fit_transform(X_new[:,7])
X_new[:,8] = le.fit_transform(X_new[:,8])
X_new[:,9] = le.fit_transform(X_new[:,9])
print(X_new)

[[925.5 3365 256066.32 ... 1 1 63]
 [134.33 4794 43879.02 ... 2 1 64]
 [147.29 870 36881.86 ... 1 1 62]
 ...
 [99.41 846 32315.46 ... 0 4 51]
 [834.47 216 429527.76 ... 1 4 47]
 [403.07 2612 164503.91 ... 0 4 23]]


In [265]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_new, y_new, test_size = 0.2, random_state = 0)

In [266]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

In [267]:
from sklearn.ensemble import RandomForestRegressor
regressor1 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor1.fit(X_train1, y_train1)

RandomForestRegressor(n_estimators=10, random_state=0)

In [268]:
y_pred1=regressor.predict(X_test1)


In [269]:
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[     0.         0.   ]
 [117806.471 106018.22 ]
 [  6143.511      0.   ]
 ...
 [     0.     40882.68 ]
 [  9618.739  17468.56 ]
 [ 87269.68   84304.96 ]]


In [270]:
print(r2_score(y_test1,y_pred1))


0.8172081677100574


In [272]:
y_pred2=regressor1.predict(test)

In [273]:
print(y_pred2)

[105290.993  77754.721      0.    ...  12384.973  70932.569  83059.363]


In [274]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(regressor1, X_test1, y_test1, scoring='r2', cv=cv, n_jobs=-1, error_score='raise')

In [275]:
print('r2: %.3f (%.3f)' % (np.mean(n_scores), np.std(n_scores)))

r2: 0.819 (0.075)


In [276]:
y_pred2=pd.Series(y_pred2,name='Loan Sanction Amount (USD)')

In [277]:
output1=pd.concat([test1['Customer ID'],y_pred2],axis=1)

In [278]:
print(min(output1['Loan Sanction Amount (USD)']))

-599.4


In [279]:
output1.to_csv('submission.csv',index=False)

In [280]:
print(output.groupby('Loan Sanction Amount (USD)').count())

                            Customer ID
Loan Sanction Amount (USD)             
-599.400                              1
-499.500                              7
-399.600                              7
-299.700                             15
-199.800                             48
...                                 ...
 275798.464                           1
 286475.291                           1
 289116.529                           1
 310611.187                           1
 351749.856                           1

[17479 rows x 1 columns]
